### ISSUE TITLE
[FEAT] Zod generation model suport of nullable

### ISSUE THREAD

**Issue by EdouardDUPIN** [kangaroo-and-rabbit/archidata#3]
the Zod generate element for the `Write` does not support the null value for all optional models

**Comment by HeeroYui** [comment]
Fixed by:
  - https://github.com/kangaroo-and-rabbit/archidata/commit/09cfcfc5786fcb91ceaa18709b415cf8e57055c6
  - https://github.com/kangaroo-and-rabbit/archidata/commit/a41e837f21926c7b258c2416cde2a731e8f2df26
